#ifndef SPLINE_GEN_HPP
#define SPLINE_GEN_HPP

#include <vector>
#include "point.hpp" // Include the Point struct

/**
 * @brief Class to generate a quintic Hermite spline from a set of waypoints.
 *
 * The class takes in a set of waypoints and generates a smooth curve that
 * passes through all the points. The generated curve is a quintic Hermite
 * spline, which is a piecewise curve that is $C^2$ continuous (i.e. has
 * continuous first and second derivatives). The curve is generated by
 * calculating the Hermite form of the curve between each pair of waypoints,
 * and then stitching the curves together.
 *
 * The class provides methods to add waypoints to the list of points to be
 * used in the generation of the spline, generate the spline, and get the
 * generated spline points.
 *
 */
class SplineGen {
public:
    SplineGen();

    void addWaypoint(const Point& waypoint);
    void generateSpline();
    const std::vector<Point>& getSpline() const;

private:
    std::vector<Point> waypoints; // List of waypoints
    std::vector<Point> spline; // Generated spline points

    void calculateQuinticHermiteSpline();
};

#endif // SPLINE_GEN_HPP